runner:
  client:
    datadirs:
      besu:
        source_dir: /data-zfs/snapshots/besu/mainnet/24350000/
        method: zfs
      geth:
        source_dir: /data-zfs/snapshots/geth/mainnet/24350000/
        method: zfs
      nethermind:
        source_dir: /data-zfs/snapshots/nethermind/mainnet/24350000/
        method: zfs
      reth:
        source_dir: /data-zfs/snapshots/reth/mainnet/24350000/
        method: zfs
      erigon:
        source_dir: /data-zfs/snapshots/erigon/mainnet/24350000/
        method: zfs
