runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: mainnet-24350000-compute
          chain: mainnet
          block: "24350000"
          test-type: compute
      source:
        git:
          repo: https://github.com/nethermindeth/gas-benchmarks.git
          version: e5011aa5f75d7a1722481f25408347fadfb7fd3c
          pre_run_steps:
            - repricings_compute/mainnet/gas-bump.txt
            - repricings_compute/mainnet/funding.txt
          steps:
            setup:
              - repricings_compute/mainnet/setup/*
            test:
              - repricings_compute/mainnet/testing/*
            cleanup:
              - repricings_compute/mainnet/cleanup/*
