benchmark:
  results_upload:
    s3:
      enabled: true
      endpoint_url: ${S3_ENDPOINT_URL}
      region: us-east-1
      bucket: benchmarkoor-results
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      prefix: repricings/results
