client:
  config:
    genesis:
      besu: https://gist.githubusercontent.com/skylenet/f15527a3d2ef4223fb95703c1d4d6c7b/raw/aaddcf9b416f201eab39b41d46203e35c1df9f68/genesis-perf-devnet-2-23861500-osaka-besu.json
      erigon: https://gist.githubusercontent.com/skylenet/a2cc1ba3801e3ab027483c819d13d522/raw/d4a941d72ad008fe97266baaf4b46c19fe116533/genesis-perf-devnet-2-23861500-osaka-genesis.json
      geth: https://gist.githubusercontent.com/skylenet/a2cc1ba3801e3ab027483c819d13d522/raw/d4a941d72ad008fe97266baaf4b46c19fe116533/genesis-perf-devnet-2-23861500-osaka-genesis.json
      nethermind: https://raw.githubusercontent.com/ethpandaops/perf-devnets/refs/heads/master/network-configs/devnet-2/metadata/chainspec.json
      reth: https://gist.githubusercontent.com/skylenet/a2cc1ba3801e3ab027483c819d13d522/raw/d4a941d72ad008fe97266baaf4b46c19fe116533/genesis-perf-devnet-2-23861500-osaka-genesis.json
