runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-2-24350000-compute
          chain: perf-devnet-2
          block: "23861500"
          test-type: compute
      source:
        git:
          repo: https://github.com/nethermindeth/gas-benchmarks.git
          version: e5011aa5f75d7a1722481f25408347fadfb7fd3c
          pre_run_steps:
            - repricings_compute/perf-devnet-2/funding.txt
          steps:
            setup:
              - repricings_compute/perf-devnet-2/setup/*/
            test:
              - repricings_compute/perf-devnet-2/testing/*
            cleanup:
              - repricings_compute/perf-devnet-2/cleanup/*
